### PR TITLE
Fix compilation with libdrm-2.4.130

### PR DESCRIPTION
**Pull request by AngryLoki**
## Motivation

Originally reported in https://bugs.gentoo.org/967246. amdsmi fails to compile with the latest libdrm-2.4.130 with error: redefinition of 'struct drm_color_ctm_3x4'.

drm_color_ctm_3x4 structure is now defined in https://github.com/torvalds/linux/commit/e5719e7f19009d4fbedf685fc22eec9cd8de154f#diff-4c51fb416ec7cc69566cd7b795ee57eb070aa1006ad65d6962081f039ffb2718

## Technical Details

As this structure is unused and not a part of amdsmi public interface, it is safe to remove it.

## Test Plan

N/A, it's a dead code removal, which fixes compilation error.

## Test Result

It compiles with libdrm-2.4.130

## Submission Checklist

- [x] Look over the contributing guidelines at https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.

### CODE REVIEW

**Comment by talhaHavadar** [comment]
Same for ubuntu: https://bugs.launchpad.net/ubuntu/+source/amdsmi/+bug/2140490
